name: Teatro
favicon: null
layout_spectrum: 1
typography_spectrum: 0.69199
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#525250'
    - '#75a2e6'
    - '#b3bfd9'
    - '#111111'
    - '#feffff'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
