name: Teatro
favicon: null
layout_spectrum: 0.435499178012833
typography_spectrum: 0.73206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6B0C22'
    - '#D9042B'
    - '#F4CB89'
    - '#588C8C'
    - '#011C26'
  brandStrength: 0.9070412979926914
  lightness: 0.83821981260553
  saturation: 0.19493623916059732
  rhythmicContrast: 0.8370882782619447
purpose: []
