name: Teatro
favicon: null
layout_spectrum: 1
typography_spectrum: 0.94825
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3184106429107487
  lightness: 0.29438872286118567
  saturation: 0.4373778742738068
  rhythmicContrast: 0.010174211813136935
purpose: []
